---
title: "Analysis of Relationship Between Physical Activity and Weight of High Schoolers"
author: "Rasul Rasulov"
date: "2020-09-21"
output:
  html_document:
    theme: flatly
    highlight: zenburn
    number_sections: yes
    toc: yes
    toc_float: yes
    code_folding: show
---



<div id="youth-risk-behavior-surveillance" class="section level1">
<h1>Youth Risk Behavior Surveillance</h1>
<p>Every two years, the Centers for Disease Control and Prevention conduct the <a href="https://www.cdc.gov/healthyyouth/data/yrbs/index.htm">Youth Risk Behavior Surveillance System (YRBSS)</a> survey, where it takes data from high schoolers (9th through 12th grade), to analyze health patterns. We work with a selected group of variables from a random sample of observations during one of the years the YRBSS was conducted.</p>
<div id="load-the-data" class="section level2">
<h2>Load the data</h2>
<p>This data is part of the <code>openintro</code> textbook and we can load and inspect it. There are observations on 13 different variables, some categorical and some numerical.</p>
<pre class="r"><code>data(yrbss) # loading the data
glimpse(yrbss) #having a glimpse on the data</code></pre>
<pre><code>## Rows: 13,583
## Columns: 13
## $ age                      &lt;int&gt; 14, 14, 15, 15, 15, 15, 15, 14, 15, 15, 15, …
## $ gender                   &lt;chr&gt; &quot;female&quot;, &quot;female&quot;, &quot;female&quot;, &quot;female&quot;, &quot;fem…
## $ grade                    &lt;chr&gt; &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;,…
## $ hispanic                 &lt;chr&gt; &quot;not&quot;, &quot;not&quot;, &quot;hispanic&quot;, &quot;not&quot;, &quot;not&quot;, &quot;not…
## $ race                     &lt;chr&gt; &quot;Black or African American&quot;, &quot;Black or Afric…
## $ height                   &lt;dbl&gt; NA, NA, 1.73, 1.60, 1.50, 1.57, 1.65, 1.88, …
## $ weight                   &lt;dbl&gt; NA, NA, 84.4, 55.8, 46.7, 67.1, 131.5, 71.2,…
## $ helmet_12m               &lt;chr&gt; &quot;never&quot;, &quot;never&quot;, &quot;never&quot;, &quot;never&quot;, &quot;did not…
## $ text_while_driving_30d   &lt;chr&gt; &quot;0&quot;, NA, &quot;30&quot;, &quot;0&quot;, &quot;did not drive&quot;, &quot;did no…
## $ physically_active_7d     &lt;int&gt; 4, 2, 7, 0, 2, 1, 4, 4, 5, 0, 0, 0, 4, 7, 7,…
## $ hours_tv_per_school_day  &lt;chr&gt; &quot;5+&quot;, &quot;5+&quot;, &quot;5+&quot;, &quot;2&quot;, &quot;3&quot;, &quot;5+&quot;, &quot;5+&quot;, &quot;5+&quot;…
## $ strength_training_7d     &lt;int&gt; 0, 0, 0, 0, 1, 0, 2, 0, 3, 0, 3, 0, 0, 7, 7,…
## $ school_night_hours_sleep &lt;chr&gt; &quot;8&quot;, &quot;6&quot;, &quot;&lt;5&quot;, &quot;6&quot;, &quot;9&quot;, &quot;8&quot;, &quot;9&quot;, &quot;6&quot;, &quot;&lt;5…</code></pre>
<p><strong>(1) - We also decided to check with dataset with <code>skimr::skim()</code> to have an idea if there are any missing values. It is also indicative of summary statistics of numerical variables, and a very rough histogram, so it worth running</strong></p>
<pre class="r"><code>skim(yrbss) #using skim function to get an idea of the dataset</code></pre>
<table style='width: auto;'
        class='table table-condensed'>
<caption>
<span id="tab:unnamed-chunk-2">Table 1: </span>Data summary
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Name
</td>
<td style="text-align:left;">
yrbss
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of rows
</td>
<td style="text-align:left;">
13583
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of columns
</td>
<td style="text-align:left;">
13
</td>
</tr>
<tr>
<td style="text-align:left;">
_______________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Column type frequency:
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
8
</td>
</tr>
<tr>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
5
</td>
</tr>
<tr>
<td style="text-align:left;">
________________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Group variables
</td>
<td style="text-align:left;">
None
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:right;">
min
</th>
<th style="text-align:right;">
max
</th>
<th style="text-align:right;">
empty
</th>
<th style="text-align:right;">
n_unique
</th>
<th style="text-align:right;">
whitespace
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
gender
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
grade
</td>
<td style="text-align:right;">
79
</td>
<td style="text-align:right;">
0.99
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
hispanic
</td>
<td style="text-align:right;">
231
</td>
<td style="text-align:right;">
0.98
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
race
</td>
<td style="text-align:right;">
2805
</td>
<td style="text-align:right;">
0.79
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
41
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
helmet_12m
</td>
<td style="text-align:right;">
311
</td>
<td style="text-align:right;">
0.98
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
text_while_driving_30d
</td>
<td style="text-align:right;">
918
</td>
<td style="text-align:right;">
0.93
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
hours_tv_per_school_day
</td>
<td style="text-align:right;">
338
</td>
<td style="text-align:right;">
0.98
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
school_night_hours_sleep
</td>
<td style="text-align:right;">
1248
</td>
<td style="text-align:right;">
0.91
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
p0
</th>
<th style="text-align:right;">
p25
</th>
<th style="text-align:right;">
p50
</th>
<th style="text-align:right;">
p75
</th>
<th style="text-align:right;">
p100
</th>
<th style="text-align:left;">
hist
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
age
</td>
<td style="text-align:right;">
77
</td>
<td style="text-align:right;">
0.99
</td>
<td style="text-align:right;">
16.16
</td>
<td style="text-align:right;">
1.26
</td>
<td style="text-align:right;">
12.00
</td>
<td style="text-align:right;">
15.0
</td>
<td style="text-align:right;">
16.00
</td>
<td style="text-align:right;">
17.00
</td>
<td style="text-align:right;">
18.00
</td>
<td style="text-align:left;">
▁▂▅▅▇
</td>
</tr>
<tr>
<td style="text-align:left;">
height
</td>
<td style="text-align:right;">
1004
</td>
<td style="text-align:right;">
0.93
</td>
<td style="text-align:right;">
1.69
</td>
<td style="text-align:right;">
0.10
</td>
<td style="text-align:right;">
1.27
</td>
<td style="text-align:right;">
1.6
</td>
<td style="text-align:right;">
1.68
</td>
<td style="text-align:right;">
1.78
</td>
<td style="text-align:right;">
2.11
</td>
<td style="text-align:left;">
▁▅▇▃▁
</td>
</tr>
<tr>
<td style="text-align:left;">
weight
</td>
<td style="text-align:right;">
1004
</td>
<td style="text-align:right;">
0.93
</td>
<td style="text-align:right;">
67.91
</td>
<td style="text-align:right;">
16.90
</td>
<td style="text-align:right;">
29.94
</td>
<td style="text-align:right;">
56.2
</td>
<td style="text-align:right;">
64.41
</td>
<td style="text-align:right;">
76.20
</td>
<td style="text-align:right;">
180.99
</td>
<td style="text-align:left;">
▆▇▂▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
physically_active_7d
</td>
<td style="text-align:right;">
273
</td>
<td style="text-align:right;">
0.98
</td>
<td style="text-align:right;">
3.90
</td>
<td style="text-align:right;">
2.56
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
2.0
</td>
<td style="text-align:right;">
4.00
</td>
<td style="text-align:right;">
7.00
</td>
<td style="text-align:right;">
7.00
</td>
<td style="text-align:left;">
▆▂▅▃▇
</td>
</tr>
<tr>
<td style="text-align:left;">
strength_training_7d
</td>
<td style="text-align:right;">
1176
</td>
<td style="text-align:right;">
0.91
</td>
<td style="text-align:right;">
2.95
</td>
<td style="text-align:right;">
2.58
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
0.0
</td>
<td style="text-align:right;">
3.00
</td>
<td style="text-align:right;">
5.00
</td>
<td style="text-align:right;">
7.00
</td>
<td style="text-align:left;">
▇▂▅▂▅
</td>
</tr>
</tbody>
</table>
<p>The table presented above indicates the extensive occurances of missing data. For “race” which scores the first in terms of the missing values, n_missing is above 2800.</p>
</div>
<div id="exploratory-data-analysis" class="section level2">
<h2>Exploratory Data Analysis</h2>
<p><strong>(2) - Our work started with analyzing the <code>weight</code> of participants in kilograms. We have calculated summary statistics. We also built a distribution plot</strong></p>
<pre class="r"><code>weight_distribution &lt;- yrbss %&gt;% 
  select(weight) %&gt;% #choosing weight variable
  filter(!is.na(weight)) %&gt;% #filtering out missing data
  summarise(mean=mean(weight),SD=sd(weight),median=median(weight),min=min(weight),max=max(weight))
#calculating statistics

  weight_distribution #showing the calculations </code></pre>
<pre><code>## # A tibble: 1 x 5
##    mean    SD median   min   max
##   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  67.9  16.9   64.4  29.9  181.</code></pre>
<pre class="r"><code>ggplot(yrbss,aes(x=weight)) + #building a plot
  geom_density()+ #choosing density plot
  labs(title=&quot;Distribution of weights appears to be roughly normal&quot;)+ #adding title
  xlab(&quot;Weight (kg)&quot;)+ #adding x-axis label
  theme_stata() #choosing theme</code></pre>
<p><img src="/blogs/Project3_files/figure-html/unnamed-chunk-3-1.png" width="648" style="display: block; margin: auto;" />
We are missing 1004 observations for the variable weight. The distribution of weights, as is shown on the diagram above, is right-skewed. However, it is still close to normal as it is roughly bell-shaped.</p>
<p><strong>(3) - Next, consider the possible relationship between a high schooler’s weight and their physical activity.</strong></p>
<pre class="r"><code>yrbss &lt;- yrbss %&gt;% 
  mutate(physical_3plus = ifelse(physically_active_7d &gt;= 3, &quot;yes&quot;, &quot;no&quot;)) #creating new variable

yrbss %&gt;% filter(!is.na(physical_3plus)) %&gt;%  #filtering out missing data
  group_by(physical_3plus) %&gt;% 
  #grouping by this new variable to calculate proportions based on its observations
  summarise(count=n()) %&gt;% #counting the answers 
  mutate(prop=count/sum(count)) #calculating the proportions </code></pre>
<pre><code>## # A tibble: 2 x 3
##   physical_3plus count  prop
##   &lt;chr&gt;          &lt;int&gt; &lt;dbl&gt;
## 1 no              4404 0.331
## 2 yes             8906 0.669</code></pre>
<p><strong>(4) - Providing a 95% confidence interval for the population proportion of high schools that are <em>NOT</em> active 3 or more days per week</strong></p>
<pre class="r"><code>not_active_CI &lt;- yrbss %&gt;%
  specify(response = physical_3plus, success=&quot;no&quot;) %&gt;% 
  #using bootstrap conf interval and choosing &quot;no&quot; as a reference for calculation
  generate(reps = 1000, type = &quot;bootstrap&quot;) %&gt;%
  calculate(stat = &quot;prop&quot;) #proportions

percentile_ci &lt;- not_active_CI %&gt;%
  get_ci(level = 0.95, type = &quot;percentile&quot;) #choosing conf level

percentile_ci</code></pre>
<pre><code>## # A tibble: 1 x 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1    0.323    0.339</code></pre>
<pre class="r"><code>visualize(not_active_CI) + #plotting the graph
  shade_ci(endpoints = percentile_ci,fill = &quot;light blue&quot;)+ #choosing shading
  geom_vline(xintercept = percentile_ci$lower_ci, colour = &quot;red&quot;)+ #paining the contours
  geom_vline(xintercept = percentile_ci$upper_ci, colour = &quot;red&quot;)+ #paining the contours
  theme_stata() #choosing the theme</code></pre>
<p><img src="/blogs/Project3_files/figure-html/unnamed-chunk-6-1.png" width="648" style="display: block; margin: auto;" />
<strong>(5) - Making a boxplot of <code>physical_3plus</code> vs. <code>weight</code>. Checking if there is a relationship between these two variables</strong></p>
<pre class="r"><code>yrbss %&gt;% 
  filter(!is.na(physical_3plus)) %&gt;% 
ggplot(aes(x=physical_3plus,y=weight)) + geom_boxplot()+
  labs(title=&quot;The relationship between weight and physical activity&quot;)+
  theme_stata()</code></pre>
<p><img src="/blogs/Project3_files/figure-html/unnamed-chunk-7-1.png" width="648" style="display: block; margin: auto;" />
As shown by the box plot, the relationship between the two variables is present. This is intuitive as both the process of gaining weight and loosing weight is highly associated with physical activity. As to distribution of answes, we can see that the median weight is slightly higher for those who exercise, but outliers in “no” group with high weight are also present which proves that physical activity prevents some obscure cases of high weight.</p>
</div>
<div id="confidence-interval" class="section level2">
<h2>Confidence Interval</h2>
<p><strong>(6) - Boxplots show how the medians of the two distributions compare, but we can also compare the means of the distributions using either a confidence interval or a hypothesis test. We calculate the mean/SD, etc weight in these groups using the mean function, we must ignore any missing values by setting the <code>na.rm = TRUE</code>.</strong></p>
<pre class="r"><code>yrbss %&gt;%
  group_by(physical_3plus) %&gt;% 
  #grouping by physical activity as we test whether the weight differ 
  #for those who is invilved in physical activity and otherwise
  filter(!is.na(physical_3plus)) %&gt;% #filtering out missing data
  summarise(mean_weight = mean(weight, na.rm = TRUE), #calculating necessary statistics
            sd_weight = sd(weight, na.rm=TRUE), #calculating necessary statistics
            count = n(),
            se_weight = sd_weight/sqrt(count), #calculating necessary statistics
            t_critical = qt(0.975, count-1), #calculating necessary statistics for 95% CI
            margin_of_error = t_critical * se_weight, #calculating necessary statistics
            lower = mean_weight - t_critical * se_weight, #calculating CI
            upper = mean_weight + t_critical * se_weight #calculating CI
            )</code></pre>
<pre><code>## # A tibble: 2 x 9
##   physical_3plus mean_weight sd_weight count se_weight t_critical
##   &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt; &lt;int&gt;     &lt;dbl&gt;      &lt;dbl&gt;
## 1 no                    66.7      17.6  4404     0.266       1.96
## 2 yes                   68.4      16.5  8906     0.175       1.96
## # … with 3 more variables: margin_of_error &lt;dbl&gt;, lower &lt;dbl&gt;, upper &lt;dbl&gt;</code></pre>
<p>There is an observed difference of about 1.77kg (68.44 - 66.67), and we notice that the two confidence intervals do not overlap. It seems that the difference is at least 95% statistically significant. Let us also conduct a hypothesis test to make sure that two different methods result in the same outcome.</p>
</div>
<div id="hypothesis-test-with-formula" class="section level2">
<h2>Hypothesis test with formula</h2>
<p><strong>(7) To conduct the test we need the null and alternative hypotheses (for testing whether mean weights are different for those who exercise at least times a week and those who don’t).</strong></p>
<p>H0: Mean weights of students who exercise 3 or more times a week = Mean weights of students who exercise who do not</p>
<p>H1: Mean weights of students who exercise 3 or more times a week != Mean weights of students who exercise who do not</p>
<pre class="r"><code>t.test(weight ~ physical_3plus, data = yrbss) #conducting t-test</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  weight by physical_3plus
## t = -5, df = 7479, p-value = 9e-08
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -2.42 -1.12
## sample estimates:
##  mean in group no mean in group yes 
##              66.7              68.4</code></pre>
</div>
<div id="hypothesis-test-with-infer" class="section level2">
<h2>Hypothesis test with <code>infer</code></h2>
<p><strong>(8) - Next, we will introduce test with function <code>hypothesize</code>, that falls into the infer workflow. We need to initialize the test, which is saved later on as <code>obs_diff</code>.</strong></p>
<pre class="r"><code>obs_diff &lt;- yrbss %&gt;%
  specify(weight ~ physical_3plus) %&gt;% #specifying the variable for which mean is 
  #calculated and the variable in which these means are going to differ
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;yes&quot;, &quot;no&quot;)) #choosing the statistics: difference in means
#choosing order to satisfy the null hypothesis of yes - no != 0
obs_diff</code></pre>
<pre><code>## # A tibble: 1 x 1
##    stat
##   &lt;dbl&gt;
## 1  1.77</code></pre>
<p><strong>(9) - After we made the test, we need to simulate the test on the null distribution, which is later on saved as null.</strong></p>
<pre class="r"><code>null_dist &lt;- yrbss %&gt;%
  specify(weight ~ physical_3plus) %&gt;% #specifying the variable for which mean is 
  #calculated and the variable in which these means are going to differ
  hypothesize(null = &quot;independence&quot;) %&gt;% #choosing test for independence as we 
  #are testing whether means are different
  generate(reps = 1000, type = &quot;permute&quot;) %&gt;% #permute is used to generate the 
  #null distribution for hypothesis test
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;yes&quot;, &quot;no&quot;))
null_dist</code></pre>
<pre><code>## # A tibble: 1,000 x 2
##    replicate    stat
##        &lt;int&gt;   &lt;dbl&gt;
##  1         1 -0.0251
##  2         2 -0.642 
##  3         3 -0.636 
##  4         4  0.296 
##  5         5  0.285 
##  6         6  0.284 
##  7         7 -0.334 
##  8         8  0.194 
##  9         9 -0.0575
## 10        10  0.455 
## # … with 990 more rows</code></pre>
<p>We use <code>hypothesize</code> to set the null hypothesis as a test for independence - the test that there is no difference between the two population means.</p>
<p>We can visualize this null distribution with the following code:</p>
<pre class="r"><code>ggplot(data = null_dist, aes(x = stat)) +
  geom_histogram(bins=20, fill=&quot;dark blue&quot;)+
  labs(title=&quot;The null distribution is normal&quot;)+
  theme_stata()</code></pre>
<p><img src="/blogs/Project3_files/figure-html/unnamed-chunk-12-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Now that the test is initialized and the null distribution formed, we can visualise to see how many of these null permutations have a difference of at least <code>obs_stat</code> of 1.77</p>
<p>In order to make a decision we use p-value, which is plotted on the histogram below using the function get_p_value</p>
<pre class="r"><code>null_dist %&gt;% visualize() +
  shade_p_value(obs_stat = obs_diff, direction = &quot;two-sided&quot;)+
  theme_stata()</code></pre>
<p><img src="/blogs/Project3_files/figure-html/unnamed-chunk-13-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>null_dist %&gt;%
  get_p_value(obs_stat = obs_diff, direction = &quot;two_sided&quot;)</code></pre>
<pre><code>## # A tibble: 1 x 1
##   p_value
##     &lt;dbl&gt;
## 1       0</code></pre>
<p>Besides having confidence interval and boxplot indicating that there is significant difference in means, we anyways conducted the hypothesis testing to provide additional confidence in the result. After conducting the necessary steps to provide the test and using visalisation techniques we actually see the distribution under null hypothesis and see the p-value. The p-value being close to zero is a clear indication that the null hypothesis is being rejected, as t-stat&gt;t-critical or significance level&gt;p-value. So using three different approaches we managed to prove that there is a difference in mean weights for those are involved in physical activity 3 or more times per week.</p>
</div>
</div>
